### PR TITLE
fix Quaternion Normalize compilation error

### LINKED ISSUE #25: problem trying to normalize a quaternion
The function `Normalize `on line 71 of QuaternionFunction.h calls a vector function `Normalized`

```
/// <summary> Returns the unit quaternion of the same direction. Does not change this object. </summary>
template <class T, bool Packed>
Quaternion<T, Packed> Normalize(const Quaternion<T, Packed>& q) {
	return Quaternion<T, Packed>{ q.vec.Normalized() };
}
```

I get a compiler error
`error C2039: 'Normalized': is not a member of 'mathter::Vector<float,4,false>'
`
Manually searching through the code, I can't to seem to find that function.

### PR DESCRIPTION
**Pull request by Tormund**
fix for https://github.com/petiaccja/Mathter/issues/25

### CODE REVIEW

**Comment by Tormund** [comment]
@petiaccja Hello, could you please check this PR?

**Comment by petiaccja** [comment]
Hey @Tormund, thanks for taking your time to fix the issue.

Could you perhaps add a test to `TestQuaternion.cpp` that verifies the correctness of your code. You can use the last test in there as a template:
```
TEST_CASE_VEC_VARIANT("Quaternion - Normalize", "[Quaternion]", TypesFloating, PackedAll) {
```

If you would like to make your PR more complete, you could also fix the `IsNormalized` method below which appears to have the same issue.

I've included a section in the `README.md` that explains how to build the tests, but you can also rely on the CI if you don't want to learn the workflow.

**Review by petiaccja — APPROVED** [review]
Looks good, thanks for your contributions!

**Comment by Tormund** [comment]
@petiaccja Getting this error on SonarQube:
```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 6:54.614s
ERROR: Error during SonarScanner execution
INFO: Final Memory: 37M/127M
ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
INFO: ------------------------------------------------------------------------
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
Error: Process completed with exit code 2.
```

**Comment by petiaccja** [comment]
That's an issue with the project's CI configuration and it can be ignored for now. The SonarCloud pipeline needs repository secrets to communicate with sonarcloud.io, but those repository secrets are not available for forks.

**Pull request merged**
